config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "notes#index"
  
  
  resources :notes do
    get 'search', on: :collection
  end


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
	paginates_per 3

	belongs_to :user

	validates_presence_of :title, :content

	def self.search(keyword)
		where("lower(title) like :keyword OR lower(content) like :keyword", keyword: "%#{keyword.downcase}%")
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def authenticate_admin_user!
    redirect_to(new_user_session_path) unless current_user.try(:admin?)
    authenticate_user!
  end

  def current_admin_user
    return nil unless current_user.try(:admin?)
    current_user
  end
end

app/controllers/note_controller.rb
class NoteController < ApplicationController

	def index
		@notes = Note.page(params[:page])
	end

	def show
		@note = Note.find(params[:id])
	end

	def search
		@keyword = params[:keyword]
		@notes = Note.search(@keyword).page(params[:page])
		render "index"
	end

	def new
		@note = Note.new
	end

	def user_params
		params.require(:note).permit(:title,:content)
	end

	def create
		@note = Note.new(user_params)
		if @note.save
			redirect_to root_path
		else
			render :new
		end
	end

	def edit
		@note = Note.find(params[:id])
	end

	def update
		@note = Note.find(params[:id])
		if @note.update(user_params)
			redirect_to root_path
		else
			render :edit
		end
	end

	def destroy
		@note = Note.find(params[:id])
		@note.destroy
		redirect_to root_path
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	skip_before_action :authenticate_user!, :only => [:index, :show, :search]

	def index
		@notes = Note.page(params[:page])
	end

	def show
		@note = Note.find(params[:id])
	end

	def search
		@keyword = params[:keyword]
		@notes = Note.search(@keyword).page(params[:page])
		render "index"
	end

	def new
		@note = Note.new
	end

	def user_params
		params.require(:note).permit(:title,:content)
	end

	def create
		@note = Note.new(user_params)
		@note.user = current_user
		if @note.save
			flash[:notice] = "You've create a new note"
			redirect_to root_path
		else
			render :new
		end
	end

	def edit
		@note = Note.find(params[:id])
	end

	def update
		@note = Note.find(params[:id])
		if @note.update(user_params)
			flash[:notice] = "You've update a note"
			redirect_to root_path
		else
			render :edit
		end
	end

	def destroy
		@note = Note.find(params[:id])
		@note.destroy
		redirect_to root_path
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def hello
		@message = params[ :message ]
	end

	def goodbye
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNotes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main">
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <%= link_to 'MyNotes', root_path, :class => "navbar-brand" %>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user.name, edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Register", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
        </ul>
        </div>
        
      </div>

      <div class="container">

        <% if flash[:notice].present? %>
          <div class="alert alert-success"><%= flash[:notice]%></div>
        <% end %>

        <% if flash[:alert].present? %>
          <div class="alert alert-danger"><%= flash[:alert]%></div>
        <% end %>

        <%= yield %>
      </div>
</div>
  </body>
</html>

app/views/note/index.html.erb
<h1>Listing notes</h1>

<div class="search">
  <%= form_tag note_search_path, :method => "get", :class => "form-inline", :role => "search" do %>
    <div class="form-group">
      <%= text_field_tag :keyword, @keyword, :class => "form-control" %>
    </div>
    <%= submit_tag "Search", :class => "btn btn-default" %>
  <% end %>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  <% @notes.each do |note| %>
    <tr>
      <td><%= note.user.name %></td>
      <td><%= note.title %></td>
      <td><%= truncate(note.content) %></td>
      <td><%= link_to 'Show', note %></td>
      <td><%= link_to 'Edit', note_edit_path(note) %></td>
      <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<div><%= paginate @notes %></div>

<%= link_to 'New Note', note_new_path, :class => "btn btn-default btn-lg" %>

app/views/notes/_form.html.erb
<%= simple_form_for @note do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <div class ="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %>
<%= link_to 'Back', note_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<div class="search">
  <%= form_tag search_notes_path, :method => "get", :class => "form-inline", :role => "search" do %>
    <div class="form-group">
      <%= text_field_tag :keyword, @keyword, :class => "form-control" %>
    </div>
    <%= submit_tag "Search", :class => "btn btn-default" %>
  <% end %>
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  <% @notes.each do |note| %>
    <tr>
      <td><%= note.user.name %></td>
      <td><%= note.title %></td>
      <td><%= truncate(note.content) %></td>
      <td><%= link_to 'Show', note %></td>
      <td><%= link_to 'Edit', edit_note_path(note) %></td>
      <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<div><%= paginate @notes %></div>

<% if user_signed_in? %>
  <%= link_to 'New Note', new_note_path, :class => "btn btn-default btn-lg" %>
<% end %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/notes/show.html.erb
<p>
  <strong>User:</strong>
  <%= @note.user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<%= link_to 'Back', notes_path %>

app/views/welcome/goodbye.html.erb
<h1>Goodbye</h1>


<%= form_tag(hello_welcome_path, :method => :get) do %>
	<%= label_tag(:message, "Message :") %>
	<%= text_field_tag(:message) %>
	<%= submit_tag("submit") %>
<% end %>

app/views/welcome/hello.html.erb
<% if @message %>
	<h1><%= @message %></h1>
<% else %><h1><%= @message %></h1>
	<h1>Hello world</h1>
<% end %>


<%= link_to "goodbye", goodbye_welcome_path %>